### ISSUE TITLE
Add webhook notification support for user confirmation operations

### ISSUE THREAD

**Issue by 2019COVID** [anthropics/claude-code#1460]
### Problem
Currently, when Claude Code encounters operations that require user confirmation, users must remain in the interactive terminal session waiting for the prompt. This creates a poor user experience for long-running tasks or when users need to step away from their terminal.

### Proposed Solution
Add configuration support for webhook notifications that can alert users when their confirmation is needed for operations such as:
- File modifications that require approval
- Potentially destructive operations
- Security-sensitive actions
- Large-scale changes

### Suggested Implementation
1. Add webhook configuration options (URL, authentication, payload format)
2. Allow users to configure webhook endpoints in settings
3. Send notifications when user confirmation is required
4. Include relevant context in webhook payload (operation type, files affected, etc.)
5. Provide a way for users to respond to confirmations remotely (optional)

### Use Cases
- Users working on long-running tasks who need to step away
- Team environments where notifications can be sent to communication channels
- CI/CD integration scenarios
- Remote development workflows

### Configuration Example
```yaml
webhooks:
  confirmation_required:
    url: "https://api.example.com/claude-notifications"
    headers:
      Authorization: "Bearer token"
    enabled: true
```

This would significantly improve the user experience by allowing asynchronous interaction with Claude Code operations.

🤖 Generated with [Claude Code](https://claude.ai/code)
