### ISSUE TITLE
How to configure the Amazon Bedrock Guardrails and Endpoint URL in the Claude-code

### ISSUE THREAD

**Issue by Sanjaya-005** [anthropics/claude-code#1830]
I am using application inference profile ARN model configured using the environment variables (access key). Now the model needs to have endpoint url and guardrail set to be able to invoke the model. In the code we do:
```python
    bedrock_runtime = boto3.client('bedrock-runtime', region_name="AWS_REGION", endpoint_url=os.getenv("AWS_ENDPOINT"))
    # Invoke the model
    response = bedrock_runtime.invoke_model(
        body=body_bytes,
        contentType=payload['contentType'],
        accept=payload['accept'],
        modelId=payload['modelId'],
        guardrailIdentifier=os.getenv("AWS_GUARDRAIL_ID"),
        guardrailVersion='1'
    )
````
So how can we configure endpoint url and amazon bedrock guardrails while using the claude-code?

**Comment by Sanjaya-005** [comment]
I am using docker to run claude-code. So I was able to configure amazon bedrock guardrails through custom headers in this manner:
```yaml
services:
  claude-code:
     environment:
         - "ANTHROPIC_CUSTOM_HEADERS=X-Amzn-Bedrock-GuardrailIdentifier: <value1>\nX-Amzn-Bedrock-GuardrailVersion: <value2>"
         - ANTHROPIC_BEDROCK_BASE_URL=<endpoint_url>
 ```
Hope this is helpful.
