### ISSUE TITLE
How to pass multiple custom headers via ANTHROPIC_CUSTOM_HEADERS

### ISSUE THREAD

**Issue by czgu** [anthropics/claude-code#1859]
This is a follow up from https://github.com/anthropics/claude-code/issues/321.

With ANTHROPIC_CUSTOM_HEADERS="Header1: Value1" I can pass in a single header, but there are no instructions on how to pass multiple headers. I tried to set ANTHROPIC_CUSTOM_HEADERS to an array or object but neither worked. 

Is this currently not supported?

**Comment by Sanjaya-005** [comment]
I am using docker to run claude-code. So I am configuring multiple custom headers in this manner:
```yaml
services:
  claude-code:
     environment:
         - "ANTHROPIC_CUSTOM_HEADERS=<Header1>: <value1>\n<Header2>: <value2>"
 ```
Hope this is helpful.
