### ISSUE TITLE
Text expanders don't fully replace the trigger text in Claude Code

### ISSUE THREAD

**Issue by teren-papercutlabs** [anthropics/claude-code#2715]
![Image](https://github.com/user-attachments/assets/ad6ecff6-af59-4bb8-8a4e-5cd3a7781254)

context:

i use Espanso to save certain phrases i use. this : para (without space) is used for "Confirm your understanding of my request by paraphrasing it back to me. Do not start any work until I confirm your understanding.". this is so i can easily use phrases i use a lot with various LLMs.

now the slash command serves a similar purpose but the problem is that they can only be triggered at the beginning of writing the message whereas i have a number of prompts that's not really a 'start the message with this' thing, it's more of i write the message 75% of the way and i'm like 'oh yeah it's good to throw that one in'. like : sa for "Use as many subagents as possible to parallelize the work."

ideal situation is that the trigger text gets replaced completely. but this is a minor issue, claude code tends to read my intent perfectly fine even with the remnants of the trigger phrase there.

**Comment by teren-papercutlabs** [comment]
Found a solution\! Posting this for anyone else experiencing similar issues with text expanders and Claude Code.

**The issue**: Espanso (and likely other text expanders) would leave behind parts of the trigger text and sometimes produce garbled output when expanding in Claude Code. This doesn't happen in other applications.

**What seems to be happening**: The default clipboard-based expansion method appears to have timing conflicts with how Claude Code processes input, possibly due to its real-time terminal rendering or input handling.

**Solution**: Switch espanso to use keyboard injection instead of clipboard paste.

**Config that fixed it** (add to `~/.config/espanso/config/default.yml` or `~/Library/Application Support/espanso/config/default.yml` on macOS):

```yaml
# Use keyboard injection instead of clipboard
backend: inject

# Lower threshold so short expansions still use fast typing
clipboard_threshold: 30

# Minimal delays to ensure trigger is fully removed
key_delay: 3      # 3ms between keystrokes
inject_delay: 1   # 1ms between injection events
```

After adding these settings, run `espanso restart`. The expansions now work perfectly - trigger text is completely removed and replacements appear correctly.

Hope this helps others using text expanders with Claude Code\!
