### ISSUE TITLE
Error: Raw mode is not supported on the current process.stdin, which Ink uses as input stream by default.

### ISSUE THREAD

**Issue by pierrekttipay** [anthropics/claude-code#404]
I am looking to run claude on a github actions CICD pipeline to review my code automatically on PRs.
I am using the command line: `claude -p "my prompt" --print` but no luck.

```
Error: Raw mode is not supported on the current process.stdin, which Ink uses as input stream by default.
Read about how to prevent this error on https://github.com/vadimdemedes/ink/#israwmodesupported
    at handleSetRawMode (file:///opt/hostedtoolcache/node/22.14.0/x64/lib/node_modules/@anthropic-ai/claude-code/cli.js:4[7](https://github.com/kttipay/banking-service/actions/runs/13747645371/job/38444607184#step:5:8)6:2045)
    at file:///opt/hostedtoolcache/node/22.14.0/x64/lib/node_modules/@anthropic-ai/claude-code/cli.js:486:2000
    at wK (file:///opt/hostedtoolcache/node/22.14.0/x64/lib/node_modules/@anthropic-ai/claude-code/cli.js:77:21381)
    at pV (file:///opt/hostedtoolcache/node/22.14.0/x64/lib/node_modules/@anthropic-ai/claude-code/cli.js:77:40838)
    at file:///opt/hostedtoolcache/node/22.14.0/x64/lib/node_modules/@anthropic-ai/claude-code/cli.js:77:39053
    at UI1 (file:///opt/hostedtoolcache/node/22.14.0/x64/lib/node_modules/@anthropic-ai/claude-code/cli.js:71:22715)
    at Immediate.zI1 [as _onImmediate] (file:///opt/hostedtoolcache/node/22.14.0/x64/lib/node_modules/@anthropic-ai/claude-code/cli.js:71:23127)
    at process.processImmediate (node:internal/timers:491:21)

  ERROR Raw mode is not supported on the current process.stdin, which Ink uses
       as input stream by default.
       Read about how to prevent this error on
       https://github.com/vadimdemedes/ink/#israwmodesupported
 - Read about how to prevent this error on
   https://github.com/vadimdemedes/ink/#israwmodesupported
 -handleSetRawM (file:///opt/hostedtoolcache/node/22.14.0/x64/lib/node_modules/
  ode          @anthropic-ai/claude-code/cli.js:476:2045)
 - (file:///opt/hostedtoolcache/node/22.14.0/x64/lib/node_modules/@anthropic-ai
  /claude-code/cli.js:4[8](https://github.com/kttipay/banking-service/actions/runs/13747645371/job/38444607184#step:5:9)6:2000)
 -wK (file:///opt/hostedtoolcache/node/22.14.0/x64/lib/node_modules/@anthropic-
    ai/claude-code/cli.js:77:21381)
 -pV (file:///opt/hostedtoolcache/node/22.14.0/x64/lib/node_modules/@anthropic-
    ai/claude-code/cli.js:77:40838)
 - (file:///opt/hostedtoolcache/node/22.14.0/x64/lib/node_modules/@anthropic-ai
  /claude-code/cli.js:77:3[9](https://github.com/kttipay/banking-service/actions/runs/13747645371/job/38444607184#step:5:10)053)
 -UI1 (file:///opt/hostedtoolcache/node/22.14.0/x64/lib/node_modules/@anthropic
     -ai/claude-code/cli.js:71:22715)
 -Immediate.z (file:///opt/hostedtoolcache/node/22.14.0/x64/lib/node_modules/@a
  1          nthropic-ai/claude-code/cli.js:71:23127)
 - process.processImmediate (node:internal/timers:491:21)
```

**Comment by tcorral** [comment]
@pierrekttipay What did you try? I am trying the same but I am also facing the same issue. I have tried different approaches, even using a Docker image. Do you think we can collaborate?

**Comment by pierrekttipay** [comment]
@tcorral I am trying to setup github action to analyse the current pull request diff and write an automated review about the code.
```
name: review-on-pr-to-main

on:
  pull_request:
    branches:
      - main

jobs:
  review:
    name: Review
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v4
      - uses: buildjet/setup-node@v3
        with:
          node-version: lts/*
          check-latest: true
      - run: npm install -g @anthropic-ai/claude-code
      - name: run claude
        id: run_claude
        env:
          TITLE: "${{github.event.pull_request.title}}"
        run: |
          claude -p "This codebase is.... I want you to perform a diff against the main branch and conduct a thorough code review for correctness, consistency, performance, scalability, security, and code quality. The current pull request title is: $TITLE" --print
      - name: Put Review in Env Var
        env:
          REVIEW: ${{join(steps.run_claude.outputs.*, '\n')}}
        run: |
          echo "REVIEW<<EOF" >> $GITHUB_ENV
          echo "$REVIEW" >> $GITHUB_ENV
          echo "EOF" >> $GITHUB_ENV
      - name: Post Review to GitHub PR
        uses: mshick/add-pr-comment@v2
        with:
          allow-repeats: true
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          repo-token-user-login: "github-actions[bot]"
          message: ${{ env.REVIEW }}
```

I think we need the claude-code core team to get involve. 
This package is fundamentally an interactive tool which makes it extremely limited.
The `-p` option is not doing enough in my opinion. The `-p` should really avoid any interactive tooling to bootstrap. 
At the moment it seems that `-p` is just a way to auto exit the interactive tool after the first answer.
The `--print` doesn't do anything it seems (maybe it's redundant with the -p, I couldn't find much doc about it)
